### ISSUE TITLE
Storybook better native layout 

### ISSUE THREAD

**Issue by kurdin** [nearform/polaris#54]
We want to create a better visual layout for stories on native. Current implementation has flaw where native storybook components not separates enough from application layout. 

Here is a screenshot of the issue. 
![image](https://user-images.githubusercontent.com/6027060/87489396-ec08d680-c610-11ea-8aba-c343edc3c54f.png)

**Comment by skywickenden** [comment]
Reopening as whilst my solution did solve the problem in component view it doesn't when on the navigation or addon tabs

**Comment by skywickenden** [comment]
I can't see a way to solve this without either forking `@storybook/react-native` or getting a PR in to fix it.

Unfortunately `@storybook/react-native` has had barely any movement in 6 months and open issues are building up.

Unlike the main storybook, there is no customisable 'preview' config file that could be used to wrap the storybook app - which is what we need to do. It is [mentioned on the roadmap](https://github.com/storybookjs/react-native/blob/master/ROADMAP.md#theme-ability-and-override-core-ui-components) 

I've created a [bug report](https://github.com/storybookjs/react-native/issues/67)

**Comment by skywickenden** [comment]
Resolved in https://github.com/nearform/polaris/pull/70
