### ISSUE TITLE
Atomic Design principles overview 

### ISSUE THREAD

**Issue by kurdin** [nearform/polaris#56]
Create Atomic Design overview in Readme with describing a basic principles for the system.

**Comment by katie-roberts** [comment]
Has this been covered in the https://github.com/nearform/polaris/blob/master/docs/polaris_UI.md ?

**Comment by katie-roberts** [comment]
Being reviewed by @matijagaspar

**Comment by matijagaspar** [comment]
The docs in https://github.com/nearform/polaris/blob/master/docs/polaris_UI.md  cover the basics, I have added a link the atomic design book, for further reading on the topic.
